AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Doc2Order Inquiry Engine

Globals:
  Function:
    Runtime: python3.12
    Timeout: 60
    MemorySize: 512

Resources:
  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc2order-inquiry-engine-ingest-dev
      Handler: src/core/ingest/handler.handler
      CodeUri: .
      Environment:
        Variables:
          APP_ENV: dev
          CUSTOMER_ID: evapo

  ClassifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc2order-inquiry-engine-classify-dev
      Handler: src/core/classify/handler.handler
      CodeUri: .
      Environment:
        Variables:
          APP_ENV: dev
          CUSTOMER_ID: evapo