SUPPORTED_FILE_TYPES = {"pdf", "xlsx"}

MATCH_STATUS_MATCHED = "MATCHED"
MATCH_STATUS_LOW_CONFIDENCE = "LOW_CONFIDENCE"
MATCH_STATUS_NO_MATCH = "NO_MATCH"
MATCH_STATUS_INVENTORY_LOOKUP_FAILED = "INVENTORY_LOOKUP_FAILED"